/**
 * Dump PostgreSQL schema (tables, columns, defaults, enums) to database/schema/.
 * Requires hr-api/.env with DATABASE_* settings and `az login` if using Entra auth.
 *
 * Usage: npm run schema:dump
 */
import { mkdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { query } from '../src/db.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = join(__dirname, '../../database/schema')

const tables = await query(`
  SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_type = 'BASE TABLE'
  ORDER BY table_name
`)

const columns = await query(`
  SELECT
    c.table_name,
    c.column_name,
    c.ordinal_position,
    c.data_type,
    c.udt_name,
    c.is_nullable,
    c.column_default,
    c.character_maximum_length
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
  ORDER BY c.table_name, c.ordinal_position
`)

const enums = await query(`
  SELECT
    t.typname AS enum_name,
    e.enumlabel AS enum_value,
    e.enumsortorder
  FROM pg_type t
  JOIN pg_enum e ON t.oid = e.enumtypid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
  ORDER BY t.typname, e.enumsortorder
`)

const columnsByTable = new Map()
for (const row of columns.rows) {
  if (!columnsByTable.has(row.table_name)) {
    columnsByTable.set(row.table_name, [])
  }
  columnsByTable.get(row.table_name).push(row)
}

const enumsByName = new Map()
for (const row of enums.rows) {
  if (!enumsByName.has(row.enum_name)) {
    enumsByName.set(row.enum_name, [])
  }
  enumsByName.get(row.enum_name).push(row.enum_value)
}

const generatedAt = new Date().toISOString()

function formatDefault(value) {
  if (value == null) return '—'
  return String(value)
}

function formatType(col) {
  if (col.data_type === 'USER-DEFINED') return col.udt_name
  if (col.character_maximum_length) {
    return `${col.data_type}(${col.character_maximum_length})`
  }
  return col.data_type
}

const md = []
md.push('# Employeedb schema reference')
md.push('')
md.push(`> Auto-generated by \`npm run schema:dump\` in \`hr-api\`.`)
md.push(`> Generated at: ${generatedAt}`)
md.push('')
md.push('Re-run after database changes to keep this file in sync with Azure PostgreSQL.')
md.push('')
md.push('## Enum types')
md.push('')
if (enumsByName.size === 0) {
  md.push('_No public enum types found._')
} else {
  for (const [name, values] of enumsByName) {
    md.push(`### \`${name}\``)
    md.push('')
    md.push(values.map(v => `- \`${v}\``).join('\n'))
    md.push('')
  }
}
md.push('## Tables')
md.push('')
for (const { table_name } of tables.rows) {
  md.push(`### \`${table_name}\``)
  md.push('')
  md.push('| Column | Type | Nullable | Default |')
  md.push('|--------|------|----------|---------|')
  for (const col of columnsByTable.get(table_name) ?? []) {
    md.push(
      `| \`${col.column_name}\` | \`${formatType(col)}\` | ${col.is_nullable} | ${formatDefault(col.column_default)} |`
    )
  }
  md.push('')
}

const json = {
  generatedAt,
  enums: Object.fromEntries(enumsByName),
  tables: Object.fromEntries(
    tables.rows.map(({ table_name }) => [
      table_name,
      (columnsByTable.get(table_name) ?? []).map(col => ({
        name: col.column_name,
        type: formatType(col),
        nullable: col.is_nullable === 'YES',
        default: col.column_default,
      })),
    ])
  ),
}

mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, 'schema.md'), md.join('\n'), 'utf8')
writeFileSync(join(outDir, 'schema.json'), JSON.stringify(json, null, 2), 'utf8')

console.log(`Wrote ${join(outDir, 'schema.md')}`)
console.log(`Wrote ${join(outDir, 'schema.json')}`)
console.log(`Tables: ${tables.rows.length}, Enum types: ${enumsByName.size}`)
